"""Add role column and other changes

Revision ID: 6b282aea5237
Revises: 
Create Date: 2025-06-12 01:46:44.242392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b282aea5237'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threat_tactic_map')
    op.drop_table('tactic')
    op.drop_table('incident')
    op.drop_table('incident_response')
    op.drop_table('risk')
    op.drop_table('threat')
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('cve_id'))

    op.drop_table('vulnerability')
    op.drop_table('incident_exploit_details')
    op.drop_table('exploit_tactic_map')
    op.drop_table('exploit')
    op.drop_table('attacker')
    op.drop_table('malware')
    with op.batch_alter_table('data_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('URL'))

    op.drop_table('data_source')
    op.drop_table('attacker_tactic_map')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('role')

    op.create_table('attacker_tactic_map',
    sa.Column('tactic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attacker_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attacker_id'], ['attacker.attacker_id'], name=op.f('attacker_tactic_map_ibfk_2')),
    sa.ForeignKeyConstraint(['tactic_id'], ['tactic.tactic_id'], name=op.f('attacker_tactic_map_ibfk_1')),
    sa.PrimaryKeyConstraint('tactic_id', 'attacker_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('data_source',
    sa.Column('source_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('platform_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('URL', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data_format', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('organization', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('reliability_score', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.PrimaryKeyConstraint('source_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('data_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('URL'), ['URL'], unique=True)

    op.create_table('malware',
    sa.Column('malware_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('family', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('behavior_desc', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('malware_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('attacker',
    sa.Column('attacker_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attacker_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('attacker_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exploit',
    sa.Column('exploit_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exploit_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('exploit_description', mysql.TEXT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('vulnerability_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerability.vulnerability_id'], name='exploit_ibfk_1'),
    sa.PrimaryKeyConstraint('exploit_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exploit_tactic_map',
    sa.Column('exploit_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tactic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exploit_id'], ['exploit.exploit_id'], name=op.f('exploit_tactic_map_ibfk_1')),
    sa.ForeignKeyConstraint(['tactic_id'], ['tactic.tactic_id'], name=op.f('exploit_tactic_map_ibfk_2')),
    sa.PrimaryKeyConstraint('exploit_id', 'tactic_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('incident_exploit_details',
    sa.Column('incident_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exploit_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attacker_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success_flag', mysql.DECIMAL(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['attacker_id'], ['attacker.attacker_id'], name=op.f('incident_exploit_details_ibfk_3')),
    sa.ForeignKeyConstraint(['exploit_id'], ['exploit.exploit_id'], name=op.f('incident_exploit_details_ibfk_2')),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.incident_id'], name=op.f('incident_exploit_details_ibfk_1')),
    sa.PrimaryKeyConstraint('incident_id', 'exploit_id', 'attacker_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vulnerability',
    sa.Column('vulnerability_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cve_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('risk_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('published_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['risk_id'], ['risk.risk_id'], name='vulnerability_ibfk_1'),
    sa.PrimaryKeyConstraint('vulnerability_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('cve_id'), ['cve_id'], unique=True)

    op.create_table('threat',
    sa.Column('threat_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('threat_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('date_detected', mysql.DATETIME(), nullable=True),
    sa.Column('risk_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('malware_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.malware_id'], name='threat_ibfk_1'),
    sa.ForeignKeyConstraint(['risk_id'], ['risk.risk_id'], name='threat_ibfk_2'),
    sa.PrimaryKeyConstraint('threat_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('risk',
    sa.Column('risk_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('risk_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('risk_level', mysql.VARCHAR(length=20), server_default=sa.text("'0'"), nullable=True),
    sa.PrimaryKeyConstraint('risk_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('incident_response',
    sa.Column('response_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('incident_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_action', mysql.TEXT(), nullable=True),
    sa.Column('response_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.incident_id'], name=op.f('incident_response_ibfk_1')),
    sa.PrimaryKeyConstraint('response_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('incident',
    sa.Column('incident_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('incident_date', mysql.DATETIME(), nullable=True),
    sa.Column('AffectedSystem_IP', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('exploit_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('threat_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AffectedSystem_OS', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('AffectedSystem_host', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('source_id', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['exploit_id'], ['exploit.exploit_id'], name=op.f('incident_ibfk_1')),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.source_id'], name=op.f('incident_ibfk_3')),
    sa.ForeignKeyConstraint(['threat_id'], ['threat.threat_id'], name=op.f('incident_ibfk_2')),
    sa.PrimaryKeyConstraint('incident_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tactic',
    sa.Column('tactic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tactic_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('tactic_type', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('tactic_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('threat_tactic_map',
    sa.Column('threat_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tactic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tactic_id'], ['tactic.tactic_id'], name=op.f('threat_tactic_map_ibfk_2')),
    sa.ForeignKeyConstraint(['threat_id'], ['threat.threat_id'], name=op.f('threat_tactic_map_ibfk_1')),
    sa.PrimaryKeyConstraint('threat_id', 'tactic_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
